import localFont from "next/font/local";
import "./globals.css";
import Provider from "../components/Provider";
import NavBar from "@/components/NavBar";


export const metadata = {
  title: "LearnStart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <NavBar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
